//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGlovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pago
    {
        public int id_detalle { get; set; }
        public Nullable<decimal> tarifa_base { get; set; }
        public Nullable<decimal> propina { get; set; }
        public Nullable<decimal> extras { get; set; }
        public Nullable<decimal> costo_recorrido { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> total { get; set; }
        public int cod_fact { get; set; }
        public int id_comisiones { get; set; }
    
        public virtual pagos pagos { get; set; }
        public virtual comisiones comisiones { get; set; }
    }
}
