//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGlovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedidos
    {
        public int id_detalle { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string nombre_producto { get; set; }
        public Nullable<decimal> total { get; set; }
        public int pedido_id_pedido { get; set; }
        public int producto_sku { get; set; }
    
        public virtual pedidos pedidos { get; set; }
        public virtual productos productos { get; set; }
    }
}
