//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGlovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresas()
        {
            this.establecimientos = new HashSet<establecimientos>();
        }
    
        public int id_empresa { get; set; }
        public string nombres { get; set; }
        public string documento { get; set; }
        public string cbu { get; set; }
        public string pais { get; set; }
        public int categoria_id { get; set; }
        public int usuario_id_us { get; set; }
        public string correo_empresa { get; set; }
    
        public virtual categorias categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<establecimientos> establecimientos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
