//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGlovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_establecimiento
    {
        public int idhe { get; set; }
        public int dia { get; set; }
        public int id_horario { get; set; }
        public Nullable<int> id_esta { get; set; }
    
        public virtual establecimientos establecimientos { get; set; }
        public virtual horario horario { get; set; }
    }
}
