//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGlovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidos()
        {
            this.comisiones = new HashSet<comisiones>();
            this.detalle_pedidos = new HashSet<detalle_pedidos>();
            this.eventos = new HashSet<eventos>();
        }
    
        public int id_pedido { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public Nullable<int> puntuacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<decimal> costo_envio { get; set; }
        public int personas_id_per { get; set; }
        public int personas_id_per1 { get; set; }
        public int sedes_id_sedes { get; set; }
        public string comprobante { get; set; }
        public Nullable<int> pagado { get; set; }
        public string destino { get; set; }
        public string origen { get; set; }
        public string firma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comisiones> comisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedidos> detalle_pedidos { get; set; }
        public virtual establecimientos establecimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventos> eventos { get; set; }
        public virtual personas personas { get; set; }
        public virtual personas personas1 { get; set; }
    }
}
