//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGlovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifas
    {
        public int id { get; set; }
        public decimal precio_base { get; set; }
        public decimal precio_km { get; set; }
        public decimal precio_espera { get; set; }
        public string descripcion { get; set; }
        public int id_glover { get; set; }
    
        public virtual personas personas { get; set; }
    }
}
